name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, macos-12]

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          brew install SDL2 SDL2_mixer SDL2_ttf SDL2_image gstreamer pkg-config

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl