name: Wheel Builder

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.cibw-build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        # - os: windows-2019
        #   python: cp38
        #   platform: win_amd64
        # - os: windows-latest
        #   python: cp39
        #   platform: win_amd64
        - os: ubuntu-latest
          python-version: 3.8
          cibw-build: cp38-manylinux_x86_64
        - os: ubuntu-latest
          python-version: 3.9
          cibw-build: cp39-manylinux_x86_64
        - os: macos-latest
          python-version: 3.8
          cibw-build: cp38-macosx_arm64
        - os: macos-latest
          python-version: 3.9
          cibw-build: cp39-macosx_arm64
        - os: macos-latest
          python-spec: cp38
          python-version: 3.8
          cibw-build: cp38-macosx_x86_64
        - os: macos-latest
          python-spec: cp39
          python-version: 3.9
          cibw-build: cp39-macosx_x86_64
        # - os: macos-latest
        #   python-spec: cp38
        #   python-version: 3.8
        #   cibw-build: cp38-macosx_arm64
        # - os: macos-latest
        #   python-spec: cp39
        #   python-version: 3.9
        #   cibw-build: cp39-macosx_arm64

    steps:
      - name: Checkout MPF-MC
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          brew install SDL2 SDL2_mixer SDL2_ttf SDL2_image gstreamer pkg-config
          pip install -U pip setuptools wheel

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_BUILD: ${{ matrix.cibw-build }}
          CIBW_BUILD_VERBOSITY: 3

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl