name: Wheel Builder

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform_id }}-${{ matrix.manylinux_image }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        platform:
          # - os: windows-2019
          #   python: cp38
          #   platform: win_amd64
          # - os: windows-latest
          #   python: cp39
          #   platform: win_amd64
          - os: ubuntu-latest
            python: cp38
            platform: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: ubuntu-latest
            python: cp39
            platform: manylinux_x86_64
            manylinux_image: manylinux2014
          - os: macos-latest
            python: cp38
            platform: macosx_x86_64
          - os: macos-latest
            python: cp39
            platform: macosx_x86_64
          - os: macos-latest
            python: cp38
            platform: macosx_arm64
          - os: macos-latest
            python: cp39
            platform: macosx_arm64

    steps:
      - name: Checkout MPF-MC
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          brew install SDL2 SDL2_mixer SDL2_ttf SDL2_image gstreamer pkg-config

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.platform }}
          CIBW_ARCHS: all
          CIBW_BUILD_VERBOSITY: 3

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl