name: Wheel Builder

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.cibw-build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          python-version: 3.7
          cibw-build: cp38-win_amd64
        - os: windows-latest
          python-version: 3.8
          cibw-build: cp38-win_amd64
        - os: windows-latest
          python-version: 3.9
          cibw-build: cp39-win_amd64
        - os: ubuntu-latest
          python-version: 3.7
          cibw-build: cp38-manylinux_x86_64
        - os: ubuntu-latest
          python-version: 3.8
          cibw-build: cp38-manylinux_x86_64
        - os: ubuntu-latest
          python-version: 3.9
          cibw-build: cp39-manylinux_x86_64
        # - os: macos-latest     # Github hosted and self-hosted ARM runners are not yet available, so I'll just build locally for now.
        #   python-version: 3.8
        #   cibw-build: cp38-macosx_arm64
        # - os: macos-latest
        #   python-version: 3.9
        #   cibw-build: cp39-macosx_arm64
        - os: macos-latest
          python-version: 3.87
          cibw-build: cp38-macosx_x86_64
        - os: macos-latest
          python-version: 3.8
          cibw-build: cp38-macosx_x86_64
        - os: macos-latest
          python-version: 3.9
          cibw-build: cp39-macosx_x86_64

    steps:
      - name: Checkout MPF-MC
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install dependencies via brew
        if: runner.os == 'macOS'  
        run: brew install SDL2 SDL2_mixer SDL2_ttf SDL2_image gstreamer pkg-config
      
      - name: Install setup dependencies via pip
        run: |
              python -m pip install --upgrade pip
              pip install --upgrade setuptools wheel build

      - name: Run cibuildwheel
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_BEFORE_ALL_LINUX:  # This is done here and not as its own step as this runs inside the cibw containered environment
            yum install -y SDL2.x86_64 SDL2-devel.x86_64 SDL2_image.x86_64 SDL2_image-devel.x86_64 SDL2_mixer.x86_64 SDL2_mixer-devel.x86_64 SDL2_ttf.x86_64 SDL2_ttf-devel.x86_64 gstreamer1.x86_64 gstreamer1-devel.x86_64
          CIBW_BUILD: ${{ matrix.cibw-build }}
          CIBW_BUILD_VERBOSITY: 3

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

# Yum packages from the manylinux container if we need them in the future.
# gstreamer1-plugins-bad-free.x86_64
# gstreamer1-plugins-bad-free-devel.x86_64
# gstreamer1-plugins-base.x86_64
# gstreamer1-plugins-base-devel.x86_64
# gstreamer1-plugins-good.x86_64
# gstreamer1-plugins-ugly-free.x86_64
# gstreamer1-plugins-ugly-free-devel.x86_64