name: Wheel Builder

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel for ${{ matrix.cibw-build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          python-version: 3.7
          cibw-build: cp37-win_amd64
        - os: windows-latest
          python-version: 3.8
          cibw-build: cp38-win_amd64
        - os: windows-latest
          python-version: 3.9
          cibw-build: cp39-win_amd64
        - os: ubuntu-latest
          python-version: 3.7
          cibw-build: cp37-manylinux_x86_64
        - os: ubuntu-latest
          python-version: 3.8
          cibw-build: cp38-manylinux_x86_64
        - os: ubuntu-latest
          python-version: 3.9
          cibw-build: cp39-manylinux_x86_64
        # - os: macos-latest     # Github hosted and self-hosted ARM runners are not yet available, so I'll just build locally for now.
        #   python-version: 3.8
        #   cibw-build: cp38-macosx_arm64
        # - os: macos-latest
        #   python-version: 3.9
        #   cibw-build: cp39-macosx_arm64
        - os: macos-latest
          python-version: 3.7
          cibw-build: cp37-macosx_x86_64
        - os: macos-latest
          python-version: 3.8
          cibw-build: cp38-macosx_x86_64
        - os: macos-latest
          python-version: 3.9
          cibw-build: cp39-macosx_x86_64

    steps:
      - name: Checkout MPF-MC
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install dependencies via brew
        if: runner.os == 'macOS'  
        run: brew install SDL2 SDL2_mixer SDL2_ttf SDL2_image gstreamer pkg-config
      
      - name: Install setup dependencies via pip
        run: |
              python -m pip install --upgrade pip
              pip install --upgrade setuptools wheel build

      - name: Run cibuildwheel
        uses: pypa/cibuildwheel@v2.8.1
        env:
          CIBW_BEFORE_ALL_LINUX:  # This is done here and not as its own step as this runs inside the cibw containered environment
            yum install -y SDL2.x86_64 SDL2-devel.x86_64 SDL2_image.x86_64 SDL2_image-devel.x86_64 SDL2_mixer.x86_64 SDL2_mixer-devel.x86_64 SDL2_ttf.x86_64 SDL2_ttf-devel.x86_64 gstreamer1.x86_64 gstreamer1-devel.x86_64
          CIBW_BUILD: ${{ matrix.cibw-build }}
          CIBW_BUILD_VERBOSITY: 3
          CIBW_TEST_COMMAND: >
            pwd &&
            ls &&
            python -m unittest discover -s mpfmc/tests

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build SDist
      run: |
        sudo apt-get -y install python3.9 python3-pip build-essential git python3-dev libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev libsdl2-mixer-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-base gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly libgstreamer1.0-dev libxine2-ffmpeg libsmpeg-dev libswscale-dev libavformat-dev libavcodec-dev libjpeg-dev libtiff5-dev libx11-dev libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev xvfb pulseaudio
        pip install --upgrade setuptools wheel build
        python -m build --sdist

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz

  upload_all:  # only if this release has a tag and is a push from us (e.g. not a pull request)
    needs: [build_wheels, make_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

# Yum packages from the manylinux container if we need them in the future.
# gstreamer1-plugins-bad-free.x86_64
# gstreamer1-plugins-bad-free-devel.x86_64
# gstreamer1-plugins-base.x86_64
# gstreamer1-plugins-base-devel.x86_64
# gstreamer1-plugins-good.x86_64
# gstreamer1-plugins-ugly-free.x86_64
# gstreamer1-plugins-ugly-free-devel.x86_64